require("conform").setup({
	notify_on_error = true,
	formatters_by_ft = {
		-- prettier
		typescriptreact = { "prettier" },
		javascriptreact = { "prettier" },
		htmlangular = { "prettier" },
		javascript = { "prettier" },
		typescript = { "prettier" },
		json = { "prettier" },
		vue = { "prettier" },
		css = { "prettier" },
		scss = { "prettier" },
		--
		typst = { "typstyle" },
		lua = { "stylua" },
		python = { "autopep8" },
		go = { "gofumpt" },
		ruby = { "rubocop" },
		rust = { "rustfmt" },
		zsh = { "beautysh" },
		sh = { "shfmt" },
		yaml = { "yamlfmt" },
		html = { "htmlbeautifier" },
		bib = { "bibtex-tidy" },
		xml = { "xmlformat" },
		cs = { "csharpier" },
		sql = { "sql_formatter" },
	},
})
