return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	event = { "VeryLazy" },
	opts_extend = { "ensure_installed" },
	cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
	opts = {
		indent = { enable = true },
		highlight = { enable = true },
		folds = { enable = true },
		ensure_installed = {
			"bash",
			"diff",
			"html",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"python",
			"regex",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"vue",
			"go",
		},
	},
	config = function(_, opts)
		local TS = require("nvim-treesitter")
		TS.setup(opts)
	end,
}
